Switch to has_work_type.
Upon further inspection, it appears work_type is a reserved
property.  This causes import to break with a NoMethodError -
undefined method `method_defined?' for nil:NilClass.